### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by qsefthuopq**

### CODE REVIEW

**Comment by SuperCoder7979** [comment]
Um, I was planning on finally getting around to localizing every biome soon. Do you think you can remake the PR once I do that?

**Comment by qsefthuopq** [comment]
Yes.
Then what does "Geyser" do?

**Comment by SuperCoder7979** [comment]
It's a geological vent that creates steam every so often. Here's the [wikipedia article](https://en.wikipedia.org/wiki/Geyser) that goes into more depth.

**Comment by SuperCoder7979** [comment]
Gonna merge this. Thank you!

**Pull request merged**
